name: build website

on:
  workflow_dispatch:
#   push:
#     branches: [ main ]
#   pull_request:
#     branches: [ main ]

concurrency: 
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build:
    runs-on: [ubuntu-latest]
    timeout-minutes: 60
    env:
      ACTIONS_ALLOW_UNSECURE_COMMANDS: true

    steps:
        
    # - name: install stork
    #   run: cargo install stork-search --locked

    - name: checkout the repo
      uses: actions/checkout@v2
      with:
        token: ${{ secrets.ACCESS_TOKEN }}
        
    - uses: actions/setup-python@v2
      with:
        python-version: '3.9'
        cache: 'pip'

    - name: install python dependencies
      run: pip3 install bibtexparser==2.0.0b3 pelican-search markdown requests
    
    - name: install stork
      uses: taiki-e/cache-cargo-install-action@v1
      with:
        tool: stork-search

    - name: GITHUB CONTEXT
      run: echo "$GITHUB_CONTEXT"
      env:
        GITHUB_CONTEXT: ${{ toJson(github) }}

    - name: get commit message
      run: |
         echo ::set-env name=commitmsg::$(git log --format=%B -n 1 ${{ github.event.after }})

    - name: show commit message
      run : echo $commitmsg

    - name: build website
      run: set -o xtrace && ./build.sh

    # - name: checkout the website branch
    #   uses: actions/checkout@v2
    #   with:
    #     repository: 'lclem/bibliographer'
    #     path: './website/'
    #     ref: 'web'
    #     token: ${{ secrets.ACCESS_TOKEN }}

    # - name: copy website
    #   run: rm -fr ./website/docs && mv ./docs ./website

    # - name: Commit website repo
    #   uses: stefanzweifel/git-auto-commit-action@v4.1.6
    #   with:
    #     repository: './website/'
    #     commit_message: update website, commit message was "${{ env.commitmsg }}"

    - name: Commit main repo
      uses: stefanzweifel/git-auto-commit-action@v4.1.6
      with:
        commit_message: update main repo, commit message was "${{ env.commitmsg }}"
